name: "Setup Zsh Development Environment"
description: "Complete setup for Zsh development including dependencies"
inputs:
  install-build-tools:
    description: "Install build tools (autoconf, automake, etc.)"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Setup Zsh
      uses: z-shell/.github/actions/setup-zsh@main
    - name: Install build tools
      if: inputs.install-build-tools == 'true'
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          brew install autoconf automake
        fi
