labels: [general]
body:
  - type: dropdown
    id: topic
    attributes:
      label: Select Topic Area
      description: What would you like to discuss?
      options:
        - "Show & Tell"
        - "Question"
        - "Feedback"
        - "General"
        - "Request"
        - "Bug"
    validations:
      required: true
  - type: textarea
    id: text
    attributes:
      label: Body
      description: Start your discussion!
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this discussion, you agree to follow our [Code of Conduct](https://github.com/z-shell/.github/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
