---
name: "Determine Git Branch"
description: "Determines the correct branch name for PR vs push events"
outputs:
  branch:
    description: "The determined branch name"
    value: ${{ steps.branch.outputs.branch }}

runs:
  using: "composite"
  steps:
    - name: Determine Branch
      id: branch
      shell: bash
      env:
        HEAD_REF: ${{ github.head_ref }}
        REF_NAME: ${{ github.ref_name }}
        EVENT_NAME: ${{ github.event_name }}
      run: |
        if [ "$EVENT_NAME" = "pull_request" ]; then
          echo "branch=$HEAD_REF" >> $GITHUB_OUTPUT
        else
          echo "branch=$REF_NAME" >> $GITHUB_OUTPUT
        fi
        echo "Determined branch: $(cat $GITHUB_OUTPUT | grep branch= | cut -d= -f2)"
