---
name: "Build Zsh Module"
description: "Build and test a Zsh module with CI-friendly configure options"
inputs:
  module-name:
    description: "Name of the module to build"
    required: true
  configure-options:
    description: "Additional configure options"
    required: false
    default: "--with-tcsetpgrp --disable-gdbm --disable-pcre"
  target-directory:
    description: "Target directory for build"
    required: false
    default: "$(pwd)"
runs:
  using: "composite"
  steps:
    - name: Configure module
      shell: bash
      run: |
        ./configure ${{ inputs.configure-options }}
    - name: Build module
      shell: bash
      run: make
    - name: Verify module build
      shell: bash
      run: |
        ls -la ./Src/zi/${{ inputs.module-name }}.*
        echo "✅ Module ${{ inputs.module-name }} built successfully"
    - name: 🔨 Build zpmod module
      env:
        BRANCH_NAME: ${{ steps.branch.outputs.branch }}
      run: |
        sh ./Scripts/install.sh --no-git --target=$(pwd) --branch="$BRANCH_NAME"
        ls -la ./Src/zi
        echo "✅ ${{ matrix.platform }} build completed successfully"
