name: "GitHub Action - verify PR labels"
author: "z-shell"
description: "Verify that pull-request has correct labels"
branding:
  icon: "check"
  color: "green"
inputs:
  github-token:
    description: "The GitHub token"
    required: true
  valid-labels:
    description: "List of valid labels"
    required: true
  invalid-labels:
    description: "List of invalid labels"
    required: false
    default: ""
  pull-request-number:
    description: "The Pull Request number"
    required: false
  disable-reviews:
    description: "Should the action post reviews on PRs"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.valid-labels }}
    - ${{ inputs.invalid-labels }}
    - ${{ inputs.pull-request-number }}
    - ${{ inputs.disable-reviews }}
