---
name: "🆗 Commit"

on: [push]

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - run: |
          echo "Something to be commited"
          date > date.txt
      - name: "🆗 Commit"
        uses: z-shell/.github/actions/commit@main
        with:
          # Git commit message (optional).
          commitMessage: ${{ github.sha }}
          # To specify a directory other than the repository root to check for changed files (optional).
          workDir: .
          # Commit user and email (optional).
          commitUserName: ${{ secrets.ACTIONS_USER }}
          commitUserEmail: ${{ secrets.ACTIONS_MAIL }}
