---
name: Project Tracker

on:
  issues:
    types: [opened, labeled, reopened]

permissions:
  contents: read
  issues: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.node_id }}
  cancel-in-progress: true

jobs:
  add-tracked-issue:
    if: contains(github.event.issue.labels.*.name, 'meta:org-tracked')
    uses: z-shell/.github/.github/workflows/project-tracker.yml@main
    with:
      issue_url: ${{ github.event.issue.html_url }}
    secrets: inherit
