---
name: "🔄 Rclone"
# Working examples:
# https://github.com/z-shell/wiki/blob/main/.github/workflows/rclone.yml
# https://github.com/z-shell/src/blob/main/.github/workflows/rclone-action.yml

on:
  push:
    paths:
      - "static/**"
  workflow_dispatch: {}

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    # Limit to specific repository. (e.g: z-shell/wiki)
    #if: github.repository == 'org-or-user/repository-name'
    runs-on: ubuntu-latest
    environment: rclone
    permissions:
      contents: read
    env:
      # Source path (some/path/to/source)
      local_path: ""
      # Remote path (remote:some/remote/path)
      remote_path: ""
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: "⏫ Run rclone"
        uses: z-shell/.github/actions/rclone@6443afd4e80c4ad1f684843d6ccd0d683dc47dbc # v1.0.0
        with:
          # The RCLONE_CONFIG secret must be set to set up for rclone (required)
          config: ${{ secrets.RCLONE_CONFIG }}
          # Pass any arguments supported by rclone (required)
          args: "sync ${{ env.local_path }} ${{ env.remote_path }}"
          # Set custom location for rclone configuration file (optional)
          #config-file: ""
          # Verbose debugging and logging (optional)
          debug: false
