---
name: "⭕ Trunk Check"
on:
  push:
    branches: ["$default-branch"]
    tags: ["v*.*.*"]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  trunk:
    name: "⚡"
    uses: z-shell/.github/.github/workflows/trunk.yml@main
    secrets:
      trunk-token: ${{ secrets.TRUNK_TOKEN }}
    with:
      runs-on: "ubuntu-latest"
