---
name: "🚀 Deploy GH Pages"

on:
  workflow_run:
    workflows:
      - "🌀 Z PageSpeed Insights"
      - "🌀 Z Activity"
      - "🌀 Z Metrics"
      - "🌀 Z Reader"
    types:
      - completed
  workflow_dispatch: {}

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    permissions:
      contents: write
      pages: write
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: "🚀 Deploy Metrics to GitHub Pages"
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: metrics
          keep_files: true
          user_name: ${{ secrets.ACTIONS_USER }}
          user_email: ${{ secrets.ACTIONS_MAIL }}
