---
name: "🛳  Deploy CloudFlare Pages"
on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  deploy:
    name: 🛳  Deploying
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      deployments: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
      - name: "⤵️  Check out code from GitHub"
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: "📦 Setup pnpm"
        uses: pnpm/action-setup@v5.0.0
      - name: "⎔  Setup node"
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 18
          cache: "pnpm"
      - name: "🏗  Build"
        run: pnpm install --prod && pnpm run build
      - name: "🚀 Publish"
        uses: cloudflare/pages-action@v1.5.0
        with:
          projectName: "zsh"
          directory: "build"
          apiToken: ${{ secrets.CF_PAGES_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
