---
name: "⭐ Star"
on:
  watch:
    types: [started]

jobs:
  star:
    runs-on: ubuntu-latest
    if: github.repository == 'z-shell/.github'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - run: |
          echo -e "\nA :star: from [@${{github.actor}}](https://github.com/${{github.actor}})" >> .github/stars.md
      - uses: z-shell/.github/actions/commit@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PUSH_BRANCH: "main"
        with:
          commitMessage: "Repository star"
