---
name: 👋 Welcome message
on:
  fork:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened]
  pull_request_review_comment:
    types: [created]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: EddieHubCommunity/gh-action-community/src/welcome@b0655168a4ac6fb03e3b649d943ad2c583900c35
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "<h3>Thank you for your feedback on this project! </h3> We will endeavour to get back to you soon."
          pr-message: "<h3>Thank you for contributing to this project! </h3> Your support is much appreciated. We will endeavour to get back to you soon."
          footer: "Community <a href=https://github.com/orgs/z-shell/discussions>Discussions</a>"
