---
name: "✅ Zsh"
on:
  workflow_call:
    inputs:
      filename:
        description: "Filename pattern to search, e.g: *.zsh"
        default: 'functions/*z-a*'
        required: false
        type: string
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  zsh-matrix:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.set-matrix.outputs.files }}
    steps:
      - name: "Set matrix output"
        id: set-matrix
        run: |
          MATRIX="$(find . -type d -name 'doc' -prune -o -type f \( -iname '*.zsh' -o -iname '${{ inputs.filename }}' \) -print | jq -ncR '{"include": [{"file": inputs}]}')"
          echo "files=${MATRIX}" >> $GITHUB_OUTPUT

  zsh-n:
    runs-on: ubuntu-latest
    needs: zsh-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.zsh-matrix.outputs.output1) }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
      - name: "⚡ Install dependencies"
        run: sudo apt update && sudo apt-get install -yq zsh
      - name: "⚡ zsh -n: ${{ matrix.file }}"
        env:
          ZSH_FILE: ${{ matrix.file }}
        run: |
          zsh -n "${ZSH_FILE}"
      - name: "⚡ zcompile ${{ matrix.file }}"
        env:
          ZSH_FILE: ${{ matrix.file }}
        run: |
          zsh -fc "zcompile ${ZSH_FILE}"; rc=$?
          ls -al "${ZSH_FILE}.zwc"; exit "$rc"
